### ISSUE TITLE
FATAL -> Failed to fork

### ISSUE THREAD

**Issue by b3taboy** [rtCamp/easyengine#407]
I'm getting this error at the 
ee stack install --mail

FATAL -> Failed to fork

**Comment by rahul286** [comment]
@gau1991 is this related to Vimbadmin repo?

**Comment by b3taboy** [comment]
Yes

Do you have another suggestion how to fix this?

**Comment by gau1991** [comment]
@b3taboy Can you give me output of following command?
```
lsb_release -a
```
Also on which VPS you were using EasyEngine ?
@rahul286 This is not related to Vimbadmin repo. This might be related to our custom aptget repo function

**Comment by b3taboy** [comment]
root@install:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty

**Comment by gau1991** [comment]
@b3taboy On which VPS you were using that command?

**Comment by b3taboy** [comment]
Finished processing dependencies for ee==3.0

For EasyEngine (ee) auto completion, run the following command

source /etc/bash_completion.d/ee_auto.rc

EasyEngine (ee) installed successfully
EasyEngine (ee) help: https://rtcamp.com/easyengine/docs/


Updating EasyEngine 3.0 configuration
Removing EasyEngine 2
root@install:~# source /etc/bash_completion.d/ee_auto.rc
root@install:~# ee stack install
Nginx already installed
PHP already installed
MySQL connection is already alive
Postfix is already installed
WP-CLI is already installed
root@install:~# ee stack install --mail
Mail server is already installed
Nginx already installed
PHP already installed
MySQL connection is already alive
FATAL -> Failed to fork.

**Comment by b3taboy** [comment]
VULTR vps

**Comment by gau1991** [comment]
If possible can you give me access to server? 
You can add my public key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCfqNgxTMHWZSg+hDh3lsGPYQ9DH2mQo0zvrpyXtP5sBtk/w8pcJsPrB3LOTlVbhRVdHdR2thTHVtubSe3eg50UiCO7uXmnpU7OM0PX1JcYWWAw5dgDOxDxucHbPqJBKPtFH9Exf2+4+/h78m/Hg3XOfceYuzaYIaIkUhFG3/8/ah8+MXBvgc5IP7v7EKJIwfgFnWAec1wQBB/+G8+YAL8JR1QAtGkdAULo9lsI048M11/bQxWqTkDPHD6hCKhcseRZ5bV/IKeCZsB45GZrn2AtU2auQi2OSVBk/TOb/hlroPNj9m0BfliddlKiZms0qIxWgkMvorheOjLKXkDO5AB gaurav.astikar@rtcamp.com
```

**Comment by b3taboy** [comment]
IP: 108.61.189.167 done

**Comment by gau1991** [comment]
@b3taboy Thanks for giving me access to server,
It was issue with Percona MySQL, I fixed that, Also fixing this EasyEngine,
Can you please now try `ee stack install --mail` and let me know if it works..

**Comment by b3taboy** [comment]
Traceback (most recent call last):
  File "/usr/local/sbin/ee", line 9, in <module>
    load_entry_point('ee==3.0', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/cli/main.py", line 84, in main
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/cli/plugins/stack.py", line 1262, in install
    self.post_pref(apt_packages, packages)
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/cli/plugins/stack.py", line 866, in post_pref
    out=ee_vmb)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 747, in render
    out_text = self.output.render(data, template)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/ext/ext_mustache.py", line 91, in render
    content = self.load_template(template)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/output.py", line 175, in load_template
    content = self._load_template_from_file(template_path)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/output.py", line 119, in _load_template_from_file
    content = open(full_path, 'r').read()
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 72: ordinal not in range(128)

**Comment by gau1991** [comment]
This is strange, why its trying to use ascii codec.
let me check on your server

**Comment by gau1991** [comment]
That happened because of invalid locale, We always use UTF8 as our locale, so we never faced this issue. We will also fix this issue in  upcoming ee. I was successful to install mail.
I saved ViMbAdmin security in file `/root/salt.txt` which is useful for you while ViMbadmin login.
Thanks for server access.

**Comment by gau1991** [comment]
@b3taboy ,
We released EE 3.0.1, you can update your current EasyEngine configuration using same command
```
wget -q http://rt.cx/ee && sudo bash ee
```

**Comment by b3taboy** [comment]
I assumed that Vultr.com com sucks and i moved to DO. 
On a fresh install i did the wget -q http://rt.cx/ee && sudo bash ee
And when i add one website I get this.
Error occurred while executing command

**Comment by gau1991** [comment]
@b3taboy ,
If possible can you send me last few lines of ee log?
```
tail -50 /var/log/ee/ee.log
```

**Comment by harshadyeola** [comment]
@b3taboy 
Checkout EasyEngine 3.0.3, locale issues has been fixed in this release.

**Comment by bigwilliam** [comment]
Hey guys, I'm running EE 3.2.0 on Ubuntu 14.04.2 LTS and I'm getting this error when running `sudo ee stack status`. 

Here's a few lines from /var/log/ee/ee.log:
`2015-06-03 09:51:45,064 (DEBUG) ee : 12Cannot allocate memory
2015-06-03 09:51:45,065 (ERROR) ee : Unable to get services status of nginx
2015-06-03 09:52:02,506 (DEBUG) ee : logging initialized for 'ee' using LoggingLogHandler
2015-06-03 09:52:02,853 (DEBUG) ee : ['/usr/local/sbin/ee', 'stack', 'status']
2015-06-03 09:52:02,853 (DEBUG) ee : collecting arguments/commands for <ee.cli.controllers.base.EEBaseController object at 0x7f092170df98>
2015-06-03 09:52:02,856 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.stack.EEStackController object at 0x7f0921697390>
2015-06-03 09:52:02,857 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.stack_services.EEStackStatusController object at 0x7f0921697b00>
2015-06-03 09:52:02,861 (INFO) ee : Initializing EasyEngine Database
2015-06-03 09:52:17,952 (DEBUG) ee : 12Cannot allocate memory
2015-06-03 09:52:17,956 (ERROR) ee : Unable to get services status of nginx`
