### ISSUE TITLE
nginx error on update

### ISSUE THREAD

**Issue by xreeckz** [rtCamp/easyengine#411]
Updated ee today and ended up with this. 

Reload : nginx     [Failed]
Traceback (most recent call last):
  File "/usr/local/sbin/ee", line 9, in <module>
    load_entry_point('ee==3.0', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/main.py", line 84, in main
    app.run()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/plugins/stack.py", line 1262, in install
    self.post_pref(apt_packages, packages)
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/plugins/stack.py", line 391, in post_pref
    config.read('/etc/php5/fpm/pool.d/www.conf')
  File "/usr/lib/python3.2/configparser.py", line 689, in read
    self._read(fp, filename)
  File "/usr/lib/python3.2/configparser.py", line 994, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/lib/python3.2/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 684: ordinal not in range(128)

**Comment by gau1991** [comment]
@xreeckz ,
We fixed this in EasyEngine next release, we hope that we will release ee 3.0.1 in  few hours,

**Comment by gau1991** [comment]
@xreeckz We release EE 3.0.1, you can update your current EasyEngine configuration using same command
```
wget -q http://rt.cx/ee && sudo bash ee
```
