### ISSUE TITLE
Undeletable site?

### ISSUE THREAD

**Issue by xreeckz** [rtCamp/easyengine#413]
root@web:~# ee --debug site create game-coach.net --w3tc
 site game-coach.net already exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/main.py", line 84, in main
    app.run()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/plugins/site.py", line 231, in default
    .format(ee_domain))
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/core/logging.py", line 24, in error
    self.app.close(1)
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/foundation.py", line 722, in close
    sys.exit(code)
SystemExit: 1
root@web:~# ee site delete game-coach.net
Do you want to delete database[Y/N]: y
Do you want to delete webroot[Y/N]: y
Do you want to delete NGINX configuration [Y/N]: y
game-coach.net does not exist in database

**Comment by harshadyeola** [comment]
@xcreekz
Thanks for reporting the issue, we will be updating this soon.
```game-coach.net does not exist in database```
FYI
This is not related to MySQL database for site, its related to ee database, which was unable to find 
entry for ```game-coach.net``` in it.

**Comment by xreeckz** [comment]
Any word on how to fix it ?

**Comment by harshadyeola** [comment]
@xreeckz 
We noticed that your site create command failed in between and also it is unable to create database as it contains `-` in your site name so in the databasename.
your database not created.
Now to revert this you have to execute ```ee site delete  game-coach.net```
and type ```N``` for database and ```Y```` for rest.
We will fix this issue as soon as possible

**Comment by xreeckz** [comment]
Thanks, any ETA on when a fix will be out? 

root@web:~# ee site delete game-coach.net
Do you want to delete database[Y/N]: n
Do you want to delete webroot[Y/N]: y
Do you want to delete NGINX configuration [Y/N]: y
game-coach.net does not exist in database

I tried to create the site using 3.0.1
Got some different errors, not sure if it's of use but here they are:

root@web:~# ee --debug site create game-coach.net --w3tc
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading Wordpress           [Done]
Setting up database             Cannot create database
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/cursors.py", line 103, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/cursors.py", line 221, in _query
    conn.query(q)
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/connections.py", line 599, in query
    self._affected_rows = self._read_query_result()
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/connections.py", line 685, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/connections.py", line 867, in read
    self.first_packet = self.connection.read_packet()
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/connections.py", line 680, in read_packet
    packet.check_error()
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/connections.py", line 331, in check_error
    raise_mysql_exception(self.__data)
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/err.py", line 135, in raise_mysql_exception
    _check_mysql_exception(errinfo)
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/err.py", line 128, in _check_mysql_exception
    raise errorclass(errno,errorvalue)
pymysql.err.ProgrammingError: (1064, "#42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-coach_net' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/core/mysql.py", line 50, in execute
    cur.execute(statement)
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/cursors.py", line 108, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python3.2/dist-packages/PyMySQL3-0.4-py3.2.egg/pymysql/connections.py", line 184, in defaulterrorhandler
    raise errorclass(errorvalue)
pymysql.err.ProgrammingError: (1064, "#42000You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-coach_net' at line 1")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/main.py", line 84, in main
    app.run()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/plugins/site.py", line 463, in default
    ee_wp_creds = setupwordpress(self, data)
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/plugins/site_functions.py", line 163, in setupwordpress
    data = setupdatabase(self, data)
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/cli/plugins/site_functions.py", line 116, in setupdatabase
    .format(ee_db_name), errormsg="Cannot create database")
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/core/mysql.py", line 58, in execute
    Log.error(self, '{0}'.format(errormsg))
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0-py3.2.egg/ee/core/logging.py", line 24, in error
    self.app.close(1)
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/foundation.py", line 722, in close
    sys.exit(code)
SystemExit: 1

**Comment by gau1991** [comment]
EE 3.0.1 gives you more specific error..
I hope will fix this soon with EE 3.0.2

**Comment by gau1991** [comment]
Fixed in 3.0.2

**Comment by harshadyeola** [comment]
Fixed in ee 3.0.7
