### ISSUE TITLE
ee stack purge php

### ISSUE THREAD

**Issue by doringheorghe** [rtCamp/easyengine#415]
A little problem :)

root@test:~# ee --debug stack purge php
usage: ee (sub-commands ...) [options ...] {arguments ...}
ee: error: unrecognized arguments: php
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ee-3.0-py3.4.egg/ee/cli/main.py", line 84, in main
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 458, in _dispatch
    self._parse_args()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 435, in _parse_args
    self.app._parse_args()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 873, in _parse_args
    self._parsed_args = self.args.parse(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/ext/ext_argparse.py", line 47, in parse
    return self.parse_args(arg_list)
  File "/usr/lib/python3.4/argparse.py", line 1729, in parse_args
    self.error(msg % ' '.join(argv))
  File "/usr/lib/python3.4/argparse.py", line 2384, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib/python3.4/argparse.py", line 2371, in exit
    _sys.exit(status)
SystemExit: 2
root@test:~#

**Comment by doringheorghe** [comment]
oh i figured out. i needed to  put --php at the end. sorry !
