### ISSUE TITLE
Unable to change owner : /var/www/game-coach.net

### ISSUE THREAD

**Issue by xreeckz** [rtCamp/easyengine#418]
Yay, more errors. It's been awesome seeing how fast fixes roll out. Good job, keep it up!

root@web:~# ee --debug site create game-coach.net --w3tc
Setting up NGINX configuration  [Done]
Setting up webroot              [Done]
Downloading Wordpress           [Done]
Setting up database             [Done]
Reload : nginx     [Failed]
Unable to change owner : /var/www/game-coach.net
Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0.2-py3.2.egg/ee/core/fileutils.py", line 139, in chown
    groupid)
OSError: [Errno 2] No such file or directory: '/var/www/game-coach.net/logs/error.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0.2-py3.2.egg/ee/cli/main.py", line 84, in main
    app.run()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0.2-py3.2.egg/ee/cli/plugins/site.py", line 471, in default
    setwebrootpermissions(self, data['webroot'])
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0.2-py3.2.egg/ee/cli/plugins/site_functions.py", line 362, in setwebrootpermissions
    EEVariables.ee_php_user, recursive=True)
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0.2-py3.2.egg/ee/core/fileutils.py", line 147, in chown
    Log.error(self, "Unable to change owner : {0} ".format(path))
  File "/usr/local/lib/python3.2/dist-packages/ee-3.0.2-py3.2.egg/ee/core/logging.py", line 24, in error
    self.app.close(1)
  File "/usr/local/lib/python3.2/dist-packages/cement-2.4.0-py3.2.egg/cement/core/foundation.py", line 722, in close
    sys.exit(code)
SystemExit: 1

**Comment by harshadyeola** [comment]
@xreeckz 
```Reload : nginx [Failed]```
Give me output for ```nginx -t``` command

**Comment by xreeckz** [comment]
root@web:~# nginx -t
nginx: [emerg] "worker_rlimit_nofile" directive is duplicate in /etc/nginx/nginx.conf:4
nginx: configuration file /etc/nginx/nginx.conf test failed

I fixed the above. 

root@web:~# nginx -t
nginx: [emerg] "server_tokens" directive is duplicate in /etc/nginx/conf.d/ee-nginx.conf:5
nginx: configuration file /etc/nginx/nginx.conf test failed

So I moved it ee-nginx out of conf.d

root@web:/etc/nginx/conf.d# nginx -t
nginx: [emerg] a duplicate default server for 0.0.0.0:22222 in /etc/nginx/sites-enabled/22222.conf:5
nginx: configuration file /etc/nginx/nginx.conf test failed

And this error has me stuck.

**Comment by xreeckz** [comment]
Ok, decided to give this another crack and it turned out, it was very simple. 
There was "22222" & "22222.conf" in sites-available / enabled.

**Comment by gau1991** [comment]
@xreeckz ,
Looks like that was bug in 3.0.0, we fixed that in 3.0.1 an 3.0.2,
So I hope your EasyEngine is going well. I am closing this issue now. Feel free to reopen if you find any other issue.
