### ISSUE TITLE
I've get this error on a fresh ubuntu vps.

### ISSUE THREAD

**Issue by crapthings** [rtCamp/easyengine#558]
root@iZ25s0gxen6Z:/etc/nginx/sites-available# sudo ee site create test.com --wpfc --debug
Running pre-update checks, please wait...
Setting up NGINX configuration 	[Done]
Setting up webroot 		[Done]
Downloading Wordpress 		[Done]
Setting up database		[Done]
Installing plugin nginx-helper, please wait...
Installing plugin w3-total-cache, please wait...
Reload : nginx     [Failed]
Oops Something went wrong !!
Calling cleanup actions ...
Reload : nginx     [OK]
service nginx reload failed. check issues with `nginx -t` command.
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ee-3.2.0-py3.4.egg/ee/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.4/dist-packages/ee-3.2.0-py3.4.egg/ee/cli/plugins/site.py", line 621, in default
    Log.error(self, "Check logs for reason "
  File "/usr/local/lib/python3.4/dist-packages/ee-3.2.0-py3.4.egg/ee/core/logging.py", line 24, in error
    self.app.close(1)
  File "/usr/local/lib/python3.4/dist-packages/cement-2.4.0-py3.4.egg/cement/core/foundation.py", line 722, in close
    sys.exit(code)
SystemExit: 1

**Comment by crapthings** [comment]
root@iZ25s0gxen6Z:/etc/nginx/sites-available# tail /var/log/ee/ee.log
2015-06-01 20:43:28,815 (DEBUG) ee : EEGit: git commit at /etc/nginx
2015-06-01 20:43:28,902 (DEBUG) ee : Removing /var/www/test.com
2015-06-01 20:43:28,902 (DEBUG) ee : Removing /var/www/test.com
2015-06-01 20:43:28,963 (DEBUG) ee : dropping database `test_com`
2015-06-01 20:43:28,964 (DEBUG) ee : Exceuting MySQL Statement : drop database `test_com`
2015-06-01 20:43:29,161 (DEBUG) ee : dropping user `test_com`
2015-06-01 20:43:29,162 (DEBUG) ee : Exceuting MySQL Statement : drop user `test_com`@`localhost`
2015-06-01 20:43:29,164 (DEBUG) ee : Exceuting MySQL Statement : flush privileges
2015-06-01 20:43:29,186 (INFO) ee : service nginx reload failed. check issues with `nginx -t` command.
2015-06-01 20:43:29,186 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
root@iZ25s0gxen6Z:/etc/nginx/sites-available#

**Comment by crapthings** [comment]
root@iZ25s0gxen6Z:/etc/nginx/sites-available# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

**Comment by harshadyeola** [comment]
@crapthings 

I am closing this issue for now. As this issue is old and is fixed in later versions of EasyEngine.
Please  open ticket on community forum (http://community.rtcamp.com/c/easyengine) if you face furthur issues.
